services:
  next:
    image: danielinro/gympilot-next
    build: 
      context: ./frontend/gympilot-next
      target: runner
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - django

  django:
    image: danielinro/gympilot-django
    build: ./backend/profitpilot_django 
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8001"
    ports:
      - "8000:8001"
    env_file:
      - ./backend/profitpilot_django/profitpilot_django/.env
    volumes:
      - ./backend:/app 
    depends_on:
      - postgres

  postgres:
    image: postgres:16.1-alpine
    ports:
      - "5432"
    env_file:
      - ./backend/profitpilot_django/profitpilot_django/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
