# Generated by Django 4.2.7 on 2023-12-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_exercisetype_exercise_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='icon',
            field=models.CharField(default='default.png', max_length=100),
        ),
    ]
