# Generated by Django 5.0 on 2023-12-29 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_exercise_icon'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='trainingtemplate',
            name='exercises',
            field=models.ManyToManyField(blank=True, null=True, related_name='trainingTemplates', to='api.exercise'),
        ),
    ]
